import { DictInterface } from "../interfaces";
export declare const implementationABIDictEthereum: DictInterface<any>;
export declare const implementationABIDictPolygon: DictInterface<any>;
export declare const implementationBasePoolAddressDictEthereum: DictInterface<any>;
export declare const implementationBasePoolAddressDictPolygon: DictInterface<any>;
export declare const basePoolAddressNameDictEthereum: DictInterface<string>;
export declare const basePoolAddressNameDictPolygon: DictInterface<string>;
export declare const basePoolAddressCoinsDictEthereum: DictInterface<string[]>;
export declare const basePoolAddressCoinsDictPolygon: DictInterface<string[]>;
export declare const basePoolAddressCoinAddressesDictEthereum: DictInterface<string[]>;
export declare const basePoolAddressCoinAddressesDictPolygon: DictInterface<string[]>;
export declare const basePoolAddressDecimalsDictEthereum: DictInterface<number[]>;
export declare const basePoolAddressDecimalsDictPolygon: DictInterface<number[]>;
export declare const basePoolAddressZapDictEthereum: DictInterface<string>;
export declare const basePoolAddressZapDictPolygon: DictInterface<string>;
export declare const blackListPolygon: string[];
export declare const WETH_ADDRESS = "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2";
export declare const ETH_ADDRESS = "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee";
